"""create_optimization_tables

Revision ID: 2e2e49c90175
Revises: a399f01808fe
Create Date: 2026-06-01 23:09:49.059082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2e49c90175'
down_revision: Union[str, Sequence[str], None] = 'a399f01808fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('persona_id', sa.String(length=36), nullable=False),
    sa.Column('optimized_system_prompt', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_feedbacks_persona_id'), 'optimization_feedbacks', ['persona_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_feedbacks_persona_id'), table_name='optimization_feedbacks')
    op.drop_table('optimization_feedbacks')
    # ### end Alembic commands ###
