"""Add vision_score and vision_reasoning to ContentDraft

Revision ID: b64d239366e7
Revises: d6650e411e45
Create Date: 2026-08-22 13:18:56.536940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64d239366e7'
down_revision: Union[str, Sequence[str], None] = 'd6650e411e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_drafts', sa.Column('vision_score', sa.Integer(), nullable=True))
    op.add_column('content_drafts', sa.Column('vision_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_drafts', 'vision_reasoning')
    op.drop_column('content_drafts', 'vision_score')
    # ### end Alembic commands ###
