"""update_content_draft_approval_fields

Revision ID: c3eb1198c9c1
Revises: 215d6bb028ee
Create Date: 2026-06-01 22:41:10.008764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3eb1198c9c1'
down_revision: Union[str, Sequence[str], None] = '215d6bb028ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_drafts', sa.Column('feedback_notes', sa.Text(), nullable=True))
    op.add_column('content_drafts', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('content_drafts', sa.Column('final_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_drafts', 'final_content')
    op.drop_column('content_drafts', 'approved_at')
    op.drop_column('content_drafts', 'feedback_notes')
    # ### end Alembic commands ###
