"""add image_url to content_drafts

Revision ID: c6b03d715b63
Revises: deb945c0d5fb
Create Date: 2026-06-02 16:50:49.340479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b03d715b63'
down_revision: Union[str, Sequence[str], None] = 'deb945c0d5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_drafts', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_drafts', 'image_url')
    # ### end Alembic commands ###
