"""create_scheduling_tables

Revision ID: deb945c0d5fb
Revises: 2e2e49c90175
Create Date: 2026-06-01 23:24:18.149444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb945c0d5fb'
down_revision: Union[str, Sequence[str], None] = '2e2e49c90175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('persona_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('posting_times_json', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_configs_persona_id'), 'schedule_configs', ['persona_id'], unique=False)
    op.add_column('content_drafts', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_content_drafts_scheduled_for'), 'content_drafts', ['scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_drafts_scheduled_for'), table_name='content_drafts')
    op.drop_column('content_drafts', 'scheduled_for')
    op.drop_index(op.f('ix_schedule_configs_persona_id'), table_name='schedule_configs')
    op.drop_table('schedule_configs')
    # ### end Alembic commands ###
