"""
image_rules.py
==============
ImageRulesEngine — strict cinematic image prompt constraints
for Pollinations AI image generation.

The image should reinforce the emotional idea of the post,
not illustrate it literally.
"""

import logging
from typing import Optional, List

logger = logging.getLogger("branding_engine.generation.image_rules")


class ImageRulesEngine:
    """Provides strict image prompt constraints for the generation pipeline."""

    PREFERRED_STYLES = [
        "Editorial corporate technology photography",
        "Shot on 35mm lens",
        "Natural daylight",
        "Depth of field",
        "Minimalist composition",
        "Clean architectural framing",
        "8k resolution",
        "Photorealistic",
    ]

    FORBIDDEN_ELEMENTS = [
        "3d",
        "render",
        "illustration",
        "isometric",
        "cartoon",
        "drawing",
        "pastel",
        "toy",
        "miniature",
        "glowing neon",
        "cyberpunk",
        "blurry",
        "faces",
        "text",
    ]

    # Deterministic topic-to-visual mapping for image prompt generation.
    # Each key is matched as a substring against the topic (case-insensitive).
    TOPIC_VISUAL_MAP = {
        "architecture": "intricate mechanical brass and silver clockwork gears",
        "system": "intricate mechanical brass and silver clockwork gears",
        "data": "monolithic black granite sculpture with clean chiseled grooves",
        "database": "monolithic black granite sculpture with clean chiseled grooves",
        "ai": "architectural glass prisms refracting clean light",
        "machine learning": "architectural glass prisms refracting clean light",
        "leadership": "monolithic marble geometries",
        "management": "monolithic marble geometries",
        "python": "aerodynamic automotive engineering design, sleek carbon fiber",
        "cloud": "aerodynamic automotive engineering design, sleek carbon fiber",
        "devops": "high-speed bullet train light trails through a clean modern glass tunnel",
        "security": "high-precision mechanical vault lock mechanism",
        "startup": "high-speed bullet train light trails through a clean modern glass tunnel",
        "automation": "intricate mechanical brass and silver clockwork gears",
        "testing": "high-precision mechanical watch movements",
    }

    DEFAULT_VISUAL = "architectural glass prisms refracting clean light"

    def get_rules(self) -> str:
        """Return the complete image rules string for template injection.

        Returns:
            Formatted image rules as a plain string.
        """
        preferred = "\n".join(f"- {style}" for style in self.PREFERRED_STYLES)
        forbidden = "\n".join(f"- {elem}" for elem in self.FORBIDDEN_ELEMENTS)

        return (
            "Image Prompt Rules (if requires_image is true):\n"
            "The image should reinforce the emotional idea of the post.\n\n"
            "Preferred:\n"
            f"{preferred}\n\n"
            "Never create:\n"
            f"{forbidden}"
        )

    def build_deterministic_prompt(
        self,
        image_idea: str = "",
        topic: Optional[str] = None,
    ) -> str:
        """Wrap the LLM image idea or topic in a high-end editorial photography brief.

        Args:
            image_idea: The visual metaphor generated by the LLM (or topic fallback).
            topic: Optional topic string if image_idea is not supplied directly.

        Returns:
            A complete image generation prompt string.
        """
        idea = image_idea.strip() if image_idea else ""
        if not idea and topic:
            topic_lower = topic.lower()
            for key, visual in self.TOPIC_VISUAL_MAP.items():
                if key in topic_lower:
                    idea = visual
                    break
            if not idea:
                idea = self.DEFAULT_VISUAL
        elif not idea:
            idea = self.DEFAULT_VISUAL

        concrete_physical_subject = idea
        final_image_prompt = (
            f"Editorial corporate technology photography, {concrete_physical_subject}, "
            f"shot on 35mm lens, natural daylight, depth of field, minimalist composition, "
            f"clean architectural framing, 8k resolution, photorealistic"
        )
        negative = "--no 3d, render, illustration, isometric, cartoon, drawing, pastel, toy, miniature, glowing neon, cyberpunk, blurry, faces, text"

        prompt = f"{final_image_prompt} {negative}"

        logger.info(
            f"[IMAGE RULES] Editorial prompt built",
            extra={"image_idea": idea, "prompt_length": len(prompt)},
        )

        return prompt
