"""
image_rules.py
==============
ImageRulesEngine — strict cinematic image prompt constraints
for Pollinations AI image generation.

The image should reinforce the emotional idea of the post,
not illustrate it literally.
"""

import logging
from typing import Optional, List

logger = logging.getLogger("branding_engine.generation.image_rules")


class ImageRulesEngine:
    """Provides strict image prompt constraints for the generation pipeline."""

    PREFERRED_STYLES = [
        "Bright, vibrant 3D isometric illustration",
        "Modern tech startup style",
        "Clean white background",
        "Colorful data visualization concept",
        "Highly detailed, 8k",
        "Modular software architecture blocks",
        "Vibrant data pipelines and workflow nodes",
        "Clean geometric composition",
        "Soft colorful gradients",
    ]

    FORBIDDEN_ELEMENTS = [
        "dark",
        "moody",
        "concrete",
        "empty rooms",
        "people",
        "faces",
        "text",
        "words",
        "messy",
        "cyberpunk",
        "monochrome",
    ]

    # Deterministic topic-to-visual mapping for image prompt generation.
    # Each key is matched as a substring against the topic (case-insensitive).
    TOPIC_VISUAL_MAP = {
        "architecture": "Bright isometric 3D modular software architecture blocks connected by vibrant data streams",
        "system": "Bright isometric 3D system architecture blocks connected with colorful data paths",
        "data": "Vibrant isometric 3D colorful database blocks, data cubes, and analytics flowcharts",
        "ai": "Bright colorful isometric 3D neural network layers and data streams",
        "machine learning": "Vibrant isometric 3D model training pipelines and colorful data matrices",
        "leadership": "Bright isometric 3D tech strategy roadmap with colorful milestone blocks",
        "management": "Bright isometric 3D engineering dashboard and colorful process workflow",
        "python": "Bright isometric 3D Python code blocks, algorithms, and data structures",
        "cloud": "Bright isometric 3D cloud server infrastructure with colorful data pipes",
        "devops": "Vibrant isometric 3D CI/CD pipeline loop with colorful gear modules",
        "security": "Bright isometric 3D glowing shield protecting modular data vaults",
        "startup": "Bright isometric 3D launchpad with colorful rocket and growth charts",
        "automation": "Vibrant isometric 3D automated robotic conveyor routing colorful data packets",
        "testing": "Bright isometric 3D quality assurance checklist and testing modules",
    }

    DEFAULT_VISUAL = "Bright isometric 3D tech concept with colorful geometric modules and data visualization"

    def get_rules(self) -> str:
        """Return the complete image rules string for template injection.

        Returns:
            Formatted image rules as a plain string.
        """
        preferred = "\n".join(f"- {style}" for style in self.PREFERRED_STYLES)
        forbidden = "\n".join(f"- {elem}" for elem in self.FORBIDDEN_ELEMENTS)

        return (
            "Image Prompt Rules (if requires_image is true):\n"
            "The image should reinforce the emotional idea of the post.\n\n"
            "Preferred:\n"
            f"{preferred}\n\n"
            "Never create:\n"
            f"{forbidden}"
        )

    def build_deterministic_prompt(
        self,
        image_idea: str = "",
        topic: Optional[str] = None,
    ) -> str:
        """Wrap the LLM image idea or topic in a bright, vibrant isometric 3D visual wrapper.

        Args:
            image_idea: The visual metaphor generated by the LLM (or topic fallback).
            topic: Optional topic string if image_idea is not supplied directly.

        Returns:
            A complete image generation prompt string.
        """
        idea = image_idea.strip() if image_idea else ""
        if not idea and topic:
            topic_lower = topic.lower()
            for key, visual in self.TOPIC_VISUAL_MAP.items():
                if key in topic_lower:
                    idea = visual
                    break
            if not idea:
                idea = self.DEFAULT_VISUAL
        elif not idea:
            idea = self.DEFAULT_VISUAL

        prefix = "Bright, vibrant 3D isometric illustration, modern tech startup style, clean white background, colorful data visualization concept, highly detailed, 8k"
        negative = "--no dark, moody, concrete, empty rooms, people, faces, text, words"

        prompt = f"{prefix}, conceptual metaphor for {idea} {negative}"

        logger.info(
            f"[IMAGE RULES] Bright isometric prompt built",
            extra={"image_idea": idea, "prompt_length": len(prompt)},
        )

        return prompt
